src/Entity/GestionPage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GestionPageRepository")
 */
class GestionPage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="text")
     */
    private $Contenu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PageAssociee;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Visible;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getPageAssociee(): ?string
    {
        return $this->PageAssociee;
    }

    public function setPageAssociee(string $PageAssociee): self
    {
        $this->PageAssociee = $PageAssociee;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->Visible;
    }

    public function setVisible(bool $Visible): self
    {
        $this->Visible = $Visible;

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\ContactSimple;
use App\Entity\GestionPage;
use App\Entity\Service;
use App\Form\ContactType;
use Nette\Utils\DateTime;
use App\Repository\ServiceRepository;
use App\Repository\PartenaireRepository;
use App\Repository\DetailServiceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(
        Request $request,
        DetailServiceRepository $sousService,
        \Swift_Mailer $mailer
    ) {
        $captcha= null;
        $services = $this->getDoctrine()
            ->getRepository(Service::class)
            ->findBy(['visible'=>1]);


        $sousServices = $sousService->findBy(['visible'=>1]);


        $blocsPage = $this->getDoctrine()
            ->getRepository(GestionPage::class)
            ->findBy(['PageAssociee'=> 'Accueil', 'Visible'=> 1]);

        $client = new ContactSimple();
        $form = $this->createForm(ContactType::class, $client);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            //recaptcha
            if (isset($_POST['g-recaptcha-response'])) {
                $captcha = $_POST['g-recaptcha-response'];
            }
            if (!$captcha) {
                $this->addFlash(
                    'danger',
                    'Veuillez verifier le formulaire captcha'
                );
                return $this->redirect($request->getUri());
            }
            $secretKey = "6Lfm2KwUAAAAABOwiaCycthCaEIt68JdbJYNZc8R";
            $ip = $_SERVER['REMOTE_ADDR'];
            // post request to server
            $url = 'https://www.google.com/recaptcha/api/siteverify?secret=' .
                urlencode($secretKey) . '&response=' . urlencode($captcha);

            $response = file_get_contents($url);
            $responseKeys = json_decode($response, true);
            // should return JSON with success as true
            if ($responseKeys["success"]) {
                $entityManager = $this->getDoctrine()->getManager();
                $client->setDateMessage(new DateTime());

                $tete = $client->getNom() . ' ' . $client->getPrenom();
                $message = (new \Swift_Message())
                    ->setSubject($tete)
                    ->setFrom($this->getParameter('mailer_from'))
                    ->setTo('yves@samuel.lu')
                    ->setBody(
                        $this->renderView(
                            'Email/notificationRenseignement.html.twig',
                            ['client' => $client]
                        ),
                        'text/html'
                    );

                $mailer->send($message);

                $this->addFlash(
                    'notice',
                    'Votre message a bien été envoyé !'
                );

                $entityManager->persist($client);
                $entityManager->flush();

                return $this->redirect($request->getUri());
            } else {
                $this->addFlash(
                    'danger',
                    'Veuillez verifier le formulaire captcha'
                );
                return $this->redirect($request->getUri());
            }
        }
        return $this->render('accueil/index.html.twig', [
            'services' => $services,
            'sousServices' => $sousServices,
            'form' => $form->createView(),
            'blocs' => $blocsPage,
        ]);
    }


    /**
     * @Route("/accueil/{id}", name="accueil_service")
     */
    public function detail(DetailServiceRepository $detail_service, Service $service)
    {
        $detail_service = $detail_service->findBy(['service' => $service->getId()]);

        return $this->render('services/details.html.twig', [
            'controller_name' => 'ServicesController',
            'details' => $detail_service,
            'service' => $service
        ]);
    }
}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block content %}
    {# card #}
    <div class="headerImg text-center">
        <h1 class="slogan">Votre partenaire informatique au Luxembourg</h1>
        <a href="#nos_services">
            <div class="arrow bounce">
            </div>
        </a>
    </div>


    {% for message in app.flashes('notice') %}
        <div class="flash-notice alert alert-success text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h2><i class="fas fa-check-circle mr-2"></i>{{ message }}</h2>
        </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
        <div class="flash-notice alert alert-danger text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h2><i class="fas fa-times-circle"></i>{{ message }}</h2>
        </div>
    {% endfor %}
    <div class="container pt-5 pb-5">
        <div class="pb-5">
            <h1 id="nos_services">Nos services</h1>
        </div>
        <div class="row d-flex justify-content-center">

            {% for service in services %}
                <div class="card border-primary m-2" style="max-width: 20rem; min-width: 20rem;">
                    <div class="card-header">
                        <img class="logoService" src="./images/Service/{{ service.UrlImg }}" alt="logo service">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ service.titre }}</h4>
                        <p class="card-text">{{ service.contenu }}</p>
                    </div>
                    <div class="align-self-end m-2">
                        {% set match = 0 %}
                        {% for sousService in sousServices %}
                            {% if sousService.service.id == service.id %}
                                {% set match = match + 1 %}
                            {% endif %}
                        {% endfor %}
                        {% if match > 0 %}
                            <a class="btn btn-primary btn-sm" href="{{ path('service_detail', {'id': service.id}) }}"
                               role="button">En savoir plus</a>
                        {% else %}
                            <div class="align-self-end m-2">
                                <a class="btn btn-primary btn-sm" href="#" data-toggle="modal"
                                   data-target="#modalRegisterForm"
                                   role="button">Nous contacter</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {# fin card #}

    {# include modal #}
    {% include "contactFormModal.html.twig" %}


    <div class="parallax"></div>
    {# qui somme nous #}

    {% for bloc in blocs %}
        <div class="container pt-5 pb-5">
            <div class="row d-flex justify-content-center">
                <div class="col-5 d-flex justify-content-center">
                    <img src="./images/pages/{{ bloc.image }}" alt="{{ bloc.titre }}" class="img-fluid img-qsn">
                </div>
                <div class="col-7 align-self-center">
                    <h1>{{ bloc.titre }}</h1>
                    <p> {{ bloc.contenu }}</p>
                </div>
            </div>
        </div>
        <div class="parallax"></div>
    {% endfor %}
{% endblock %}
{% block jquery %}
    {% include 'JqueryBlock.html.twig' %}
    {% include 'jqueryContact.html.twig' %}
{% endblock %}