src/Entity/DetailService.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DetailServiceRepository")
 */
class DetailService
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="text")
     */
    private $url_img;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="detailServices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $service;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getUrlImg(): ?string
    {
        return $this->url_img;
    }

    public function setUrlImg(string $url_img): self
    {
        $this->url_img = $url_img;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }
}

src/Controller/Backoffice/DetailServiceController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\DetailService;
use App\Entity\Service;
use App\Form\DetailServiceType;
use App\Form\DetailServiceEditType;
use App\Repository\DetailServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Service\FileUploader;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Require ROLE_ADMIN for *every* controller method in this class.
 *
 * @IsGranted("ROLE_ADMIN")
 *
 * @Route("/detail/service")
 */
class DetailServiceController extends AbstractController
{
    /**
     * @Route("/", name="detail_service_index", methods={"GET"})
     */
    public function index(DetailServiceRepository $detailServiceRepository): Response
    {
        return $this->render('Backoffice/detail_service/index.html.twig', [
            'detail_services' => $detailServiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="detail_service_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $detailService = new DetailService();
        $form = $this->createForm(DetailServiceType::class, $detailService);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['UrlImg']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgSousService($imageFile);
                $detailService->setUrlImg($imageFileName);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($detailService);
            $entityManager->flush();

            return $this->redirectToRoute('detail_service_index');
        }

        return $this->render('Backoffice/detail_service/new.html.twig', [
            'detail_service' => $detailService,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="detail_service_show", methods={"GET"})
     */
    public function show(DetailService $detailService): Response
    {
        return $this->render('Backoffice/detail_service/show.html.twig', [
            'detail_service' => $detailService,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="detail_service_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, DetailService $detailService, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(DetailServiceEditType::class, $detailService);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['UrlImg']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgSousService($imageFile);
                $detailService->setUrlImg($imageFileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('detail_service_index', [
                'id' => $detailService->getId(),
            ]);
        }

        return $this->render('Backoffice/detail_service/edit.html.twig', [
            'detail_service' => $detailService,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="detail_service_delete", methods={"DELETE"})
     */
    public function delete(Request $request, DetailService $detailService): Response
    {
        if ($this->isCsrfTokenValid('delete'.$detailService->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($detailService);
            $entityManager->flush();
        }

        return $this->redirectToRoute('detail_service_index');
    }
}

src/Controller/Backoffice/GestionPageController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\GestionPage;
use App\Form\GestionPageType;
use App\Form\GestionPageEditType;
use App\Repository\GestionPageRepository;
use App\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Require ROLE_ADMIN for *every* controller method in this class.
 *
 * @IsGranted("ROLE_ADMIN")
 *
 * @Route("/gestion/page")
 */
class GestionPageController extends AbstractController
{
    /**
     * @Route("/", name="gestion_page_index", methods={"GET"})
     */
    public function index(GestionPageRepository $gestionPageRepository): Response
    {
        return $this->render('Backoffice/gestion_page/index.html.twig', [
            'gestion_pages' => $gestionPageRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="gestion_page_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $gestionPage = new GestionPage();
        $form = $this->createForm(GestionPageType::class, $gestionPage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['Image']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgPage($imageFile);
                $gestionPage->setImage($imageFileName);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($gestionPage);
            $entityManager->flush();

            return $this->redirectToRoute('gestion_page_index');
        }

        return $this->render('Backoffice/gestion_page/new.html.twig', [
            'gestion_page' => $gestionPage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gestion_page_show", methods={"GET"})
     */
    public function show(GestionPage $gestionPage): Response
    {
        return $this->render('Backoffice/gestion_page/show.html.twig', [
            'gestion_page' => $gestionPage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="gestion_page_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, GestionPage $gestionPage, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(GestionPageEditType::class, $gestionPage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['Image']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgPage($imageFile);
                $gestionPage->setImage($imageFileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('gestion_page_index', [
                'id' => $gestionPage->getId(),
            ]);
        }

        return $this->render('Backoffice/gestion_page/edit.html.twig', [
            'gestion_page' => $gestionPage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gestion_page_delete", methods={"DELETE"})
     */
    public function delete(Request $request, GestionPage $gestionPage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$gestionPage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($gestionPage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gestion_page_index');
    }
}

src/Controller/Backoffice/PartenaireController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Partenaire;
use App\Form\PartenaireType;
use App\Form\PartenaireEditType;
use App\Service\FileUploader;
use App\Repository\PartenaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Constraints\File;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Require ROLE_ADMIN for *every* controller method in this class.
 *
 * @IsGranted("ROLE_ADMIN")
 *
 * @Route("/partenaire")
 */
class PartenaireController extends AbstractController
{
    /**
     * @Route("/", name="partenaire_index", methods={"GET"})
     */
    public function index(PartenaireRepository $partenaireRepository): Response
    {
        return $this->render('Backoffice/partenaire/index.html.twig', [
            'partenaires' => $partenaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="partenaire_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $partenaire = new Partenaire();
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['urlLogo']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgPartenaire($imageFile);
                $partenaire->setUrlLogo($imageFileName);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($partenaire);
            $entityManager->flush();

            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('Backoffice/partenaire/new.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_show", methods={"GET"})
     */
    public function show(Partenaire $partenaire): Response
    {
        return $this->render('Backoffice/partenaire/show.html.twig', [
            'partenaire' => $partenaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="partenaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Partenaire $partenaire, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(PartenaireEditType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form['urlLogo']->getData();
            if (!empty($imageFile)) {
                $imageFileName = $fileUploader->uploadImgPartenaire($imageFile);
                $partenaire->setUrlLogo($imageFileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('partenaire_index', [
                'id' => $partenaire->getId(),
            ]);
        }

        return $this->render('Backoffice/partenaire/edit.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Partenaire $partenaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partenaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($partenaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('partenaire_index');
    }
}

src/Controller/Backoffice/RenseignementController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\ContactSimple;
use App\Form\ContactType;
use App\Repository\ContactSimpleRepository;
use Nette\Utils\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Require ROLE_ADMIN for *every* controller method in this class.
 *
 * @IsGranted("ROLE_ADMIN")
 *
 * @Route("/renseignement")
 */
class RenseignementController extends AbstractController
{
    /**
     * @Route("/", name="renseignement_index", methods={"GET"})
     */
    public function index(ContactSimpleRepository $contactSimpleRepository): Response
    {
        return $this->render('Backoffice/renseignement/index.html.twig', [
            'contactsSimples' => $contactSimpleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/Contact", name="contactSimple_new", methods={"GET","POST"})
     */
    public function newContactSimple(Request $request): Response
    {
        $contactSimple = new ContactSimple();
        $form = $this->createForm(ContactType::class, $contactSimple);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactSimple->setDateMessage(new DateTime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contactSimple);
            $entityManager->flush();

            return $this->redirectToRoute('renseignement_index');
        }

        return $this->render('Backoffice/renseignement/newContactSimple.html.twig', [
            'contactSimple' => $contactSimple,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/contact/{id}", name="contactSimple_show", methods={"GET"})
     */
    public function showContact(ContactSimple $contactSimple): Response
    {
        return $this->render('Backoffice/renseignement/showContactSimple.html.twig', [
            'contactSimple' => $contactSimple,
        ]);
    }

    /**
     * @Route("/{id}/editContact", name="contactSimple_edit", methods={"GET","POST"})
     */
    public function editContact(Request $request, ContactSimple $contactSimple): Response
    {
        $form = $this->createForm(ContactType::class, $contactSimple);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactSimple->setDateMessage(new DateTime());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('renseignement_index', [
                'id' => $contactSimple->getId(),
            ]);
        }

        return $this->render('Backoffice/renseignement/editContactSimple.html.twig', [
            'contactSimple' => $contactSimple,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/contact/{id}", name="contactSimple_delete", methods={"DELETE"})
     */
    public function deleteContact(Request $request, ContactSimple $contactSimple): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contactSimple->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($contactSimple);
            $entityManager->flush();
        }

        return $this->redirectToRoute('renseignement_index');
    }
}

templates/Backoffice/detail_service/_delete_form.html.twig
<form method="post" action="{{ path('detail_service_delete', {'id': detail_service.id}) }}"
      onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce sous-service ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ detail_service.id) }}">
    <button type="submit" class="btn-light">
        <img data-toggle="tooltip" data-placement="top" title="Supprimer le sous-service"
             class="iconBackofficeDelete"
             src="{{ asset('images/Icons/trash-alt-regular.svg') }}"
             alt="Supprimer le sous-service">
    </button>
</form>

templates/Backoffice/detail_service/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}
    {{ form_widget(form.UrlImg) }}

<div class="btn-group">
        <span class="btn-light">
        <a href="{{ path('detail_service_index') }}">
            <img data-toggle="tooltip" data-placement="top" title="Revenir à la liste"
                 class="iconBackoffice"
                 src="{{ asset('images/Icons/arrow-left-solid.svg') }}"
                 alt="Revenir à la liste">
        </a>
    </span>
    <span class="btn-light">
        <button class="btn enregistrer" data-toggle="tooltip" data-placement="top" title="Enregistrer">
            {{ button_label|default(' ') }}
        </button>
    </span>
</div>
{{ form_end(form) }}

templates/Backoffice/detail_service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}AccesInfoService - Backoffice - Modifier un sous-service{% endblock %}

{% block content %}
    <div class="wrapper">
        {% include('menuBackoffice.html.twig') %}
        <div class="container">
            <h1 class="pt-3 pb-3">
                Modifier le sous-service :
                <span class="titreBack">{{ detail_service.titre }}</span>.
            </h1>
            {{ include('Backoffice/detail_service/_form.html.twig', {'button_label': ' '}) }}
            <div class="iconBackofficeDeletePosition">
                {{ include('Backoffice/detail_service/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/Backoffice/detail_service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AccesInfoService - Backoffice - Les sous-services{% endblock %}

{% block content %}
    <div class="wrapper">
        {% include('menuBackoffice.html.twig') %}
        <div class="container">
            <h1 class="pt-3 pb-3">
                Gestion des sous-services -
                <span class="btn-light">
                    <a href="{{ path('detail_service_new') }}">
                        <img data-toggle="tooltip" data-placement="top" title="Ajouter un sous-service"
                             class="iconBackofficeAdd"
                             src="{{ asset('images/Icons/plus-square-regular.svg') }}"
                             alt="Ajouter un sous-service">
                    </a>
                </span>
            </h1>
            <table class="table table-striped">
                <thead>
                <tr class="table-primary">
                    <th>Identifiant</th>
                    <th>Titre</th>
                    <th>Sous-titre</th>
                    <th>Lié au service</th>
                    <th>Contenu</th>
                    <th>Nom de l'image</th>
                    <th>Visible</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for detail_service in detail_services %}
                    <tr>
                        <td>{{ detail_service.id }}</td>
                        <td>{{ detail_service.titre }}</td>
                        <td>{{ detail_service.subtitle }}</td>
                        <td>{{ detail_service.service.titre }}</td>
                        <td>{{ detail_service.contenu }}</td>
                        <td>{{ detail_service.urlImg }}</td>
                        <td>{{ detail_service.visible ? 'Oui' : 'Non' }}</td>
                        <td class="btn-group">
                            <div class="btn-light">
                                <a href="{{ path('detail_service_show', {'id': detail_service.id}) }}">
                                    <img data-toggle="tooltip" data-placement="top"
                                         title="Regarder le sous-service"
                                         class="iconBackoffice align-middle"
                                         src="{{ asset('images/Icons/search-solid.svg') }}"
                                         alt="Regarder le sous-service">
                                </a>
                            </div>
                            <div class="btn-light">
                                <a href="{{ path('detail_service_edit', {'id': detail_service.id}) }}">
                                    <img data-toggle="tooltip" data-placement="top"
                                         title="Modifier le sous-service"
                                         class="iconBackoffice"
                                         src="{{ asset('images/Icons/edit-solid.svg') }}"
                                         alt="Modifier le sous-service">
                                </a>
                            </div>
                            {{ include('Backoffice/detail_service/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">Il n'y a pas de sous-services.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/Backoffice/detail_service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}AccesInfoService - Backoffice - Ajouter un sous-service{% endblock %}

{% block content %}
    <div class="wrapper">
    {% include('menuBackoffice.html.twig') %}
        <div class="container">
            <h1 class="pt-3 pb-3">Ajouter un sous-service</h1>
            {{ include('Backoffice/detail_service/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/Backoffice/detail_service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AccesInfoService - Backoffice - Les sous-services{% endblock %}

{% block content %}
    <div class="wrapper">
        {% include('menuBackoffice.html.twig') %}
        <div class="container">
            <h1 class="pt-3 pb-3">Gestion du sous-service :
                <span class="titreBack">{{ detail_service.titre }}</span>.
            </h1>
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th>Identifiant</th>
                    <td>{{ detail_service.id }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ detail_service.titre }}</td>
                </tr>
                <tr>
                    <th>Sous-titre</th>
                    <td>{{ detail_service.subtitle }}</td>
                </tr>
                <tr>
                    <th>Lié au SERVICE</th>
                    <td>{{ detail_service.service.titre }}</td>
                </tr>
                <tr>
                    <th>Contenu</th>
                    <td>{{ detail_service.contenu }}</td>
                </tr>
                <tr>
                    <th>Nom de l'image</th>
                    <td>{{ detail_service.urlImg }}</td>
                </tr>
                <tr>
                    <th>Image</th>
                    <td>
                        <img class="logoServiceBackoffice" src="/images/Sous-service/{{ detail_service.UrlImg }}">
                    </td>
                </tr>
                <tr>
                    <th>Actions</th>
                    <td>
                        <div class="btn-group">
                            {{ include('Backoffice/detail_service/_delete_form.html.twig') }}
                            <div class="btn-light">
                                <a href="{{ path('detail_service_edit', {'id': detail_service.id}) }}">
                                    <img data-toggle="tooltip" data-placement="top"
                                         title="Modifier le sous-service"
                                         class="iconBackoffice"
                                         src="{{ asset('images/Icons/edit-solid.svg') }}"
                                         alt="Modifier le sous-service">
                                </a>
                            </div>
                            <div class="btn-light">
                                <a href="{{ path('detail_service_index') }}">
                                    <img data-toggle="tooltip" data-placement="top" title="Revenir à la liste"
                                         class="iconBackoffice"
                                         src="{{ asset('images/Icons/arrow-left-solid.svg') }}"
                                         alt="Revenir à la liste">
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}